creatures = [
    "Allosaurus",
    "Anaconda",
    "Ankheg",
    "Basilisk",
    "Bigeyes",
    "Bloodbones",
    "Buccaneer",
    "Chimera",
    "Cobra",
    "Cockatrice",
    "Crawler",
    "Croc",
    "Crocodile",
    "Deepeyes",
    "Devil",
    "Dragon",
    "Elemental",
    "Eye",
    "Fighter",
    "Flan",
    "Gargoyle",
    "Garland",
    "Ghast",
    "Ghost",
    "Ghoul",
    "Gigas",
    "Goblin",
    "Golem",
    "Guard",
    "Guardian",
    "Hellhound",
    "Horse",
    "Hydra",
    "Hyenadon",
    "Jelly",
    "Lizard",
    "Manticore",
    "Medusa",
    "Mindflayer",
    "Minotaur",
    "Mummy",
    "Naga",
    "Neochu",
    "Nightmare",
    "Ochu",
    "Ogre",
    "Ooze",
    "Piranha",
    "Pirate",
    "Piscodemon",
    "Pyrolisk",
    "Rakshasa",
    "Remorazz",
    "Rhyos",
    "Sabertooth",
    "Sahagin",
    "Scorpion",
    "Shadow",
    "Shark",
    "Skeleton",
    "Slime",
    "Snake",
    "Soldier",
    "Specter",
    "Sphinx",
    "Sylph",
    "Tarantula",
    "Tiger",
    "Troll",
    "Tyrannosaur",
    "Vampire",
    "Warg",
    "Weretiger",
    "Werewolf",
    "Widow",
    "Wight",
    "Wizard",
    "Wolf",
    "Worm",
    "Wraith",
    "Wyrm",
    "Wyvern",
    "Zombie",
]

prefixes = [
    "Air",
    "Black",
    "Blue",
    "Clay",
    "Chaos",
    "Corrupted",
    "Crazy",
    "Dark",
    "Death",
    "Desert",
    "Earth",
    "Evil",
    "Fire",
    "Gray",
    "Green",
    "Hill",
    "Horned",
    "Ice",
    "Iron",
    "Lava",
    "Lesser",
    "Light",
    "Mage",
    "Ochre",
    "Sparkle",
    "Purple",
    "Red",
    "Sand",
    "Sea",
    "Spirit",
    "Summer",
    "Spring",
    "Autum",
    "Fall",
    "Stone",
    "Undead",
    "Water",
    "Were",
    "White",
    "Winter",
]

titles = [
    "Chief",
    "Common",
    "Cuddly",
    "Duke",
    "Dutches",
    "Guard",
    "King",
    "Knight",
    "Lady",
    "Lord",
    "Magistrate",
    "Prince",
    "Princess",
    "Queen",
    "Supreme",
    "Tough",
]